### ISSUE TITLE
 Unsupported primitive of type: Interp name: base/layer_14/output/upsample with the CPU models. 

### ISSUE THREAD

**Issue by rakidedigama** [PINTO0309/MobileNetV2-PoseEstimation#1]
Hi. Great work. Still, I am getting an error with the CPU models on Windows with Openvino. Can you help me with this please? Thanks.

**Comment by flerkenvn** [comment]
I got the same issue.

**Comment by PINTO0309** [comment]
Please tell me everything below.
1. what kind of model file was used
2. what kind of program was run
3. openvino version 1.0 or 1.0.1 or other

**Comment by flerkenvn** [comment]
> Please tell me everything below.
> 
> 1. what kind of model file was used
> 2. what kind of program was run
> 3. openvino version 1.0 or 1.0.1 or other

 I used model file: "models/train/test/openvino/mobilenet_v2_1.4_224/FP32/frozen-model.xml" with command "python3 openvino-usbcamera-cpu-ncs2-sync.py -d CPU"
with OpenVino 2019 R1.133

**Comment by rakidedigama** [comment]
I used almost the same configurations. However, I was testing this with openvino windows Release 1.0.1, and it seems that the version does not support certain layers.

> Shape inference for Interp layer works for almost all cases, except for Caffe models with fixed width and height parameters (for example, semantic-segmentation-adas-0001).
 
https://software.intel.com/en-us/articles/OpenVINO-RelNotes - known issues #21 : 

Here's a screenshot of the error. 
![image](https://user-images.githubusercontent.com/26470435/57692447-717ca980-764f-11e9-8c13-413388f5c4b3.png)

**Comment by PINTO0309** [comment]
You must use CPU extensions.
**`lib/libcpu_extension.so`**
Also, OpenVINO for Windows seems to be unstable.
I strongly recommend the use of Ubuntu.

```python
if "CPU" == args.device:
    if platform.processor() == "x86_64":
        plugin.add_cpu_extension("lib/libcpu_extension.so")
    if args.boost == False:
        model_xml = "models/train/test/openvino/mobilenet_v2_1.4_224/FP32/frozen-model.xml"
    else:
        model_xml = "models/train/test/openvino/mobilenet_v2_0.5_224/FP32/frozen-model.xml"

elif "GPU" == args.device or "MYRIAD" == args.device:
    if args.boost == False:
        model_xml = "models/train/test/openvino/mobilenet_v2_1.4_224/FP16/frozen-model.xml"
    else:
        model_xml = "models/train/test/openvino/mobilenet_v2_0.5_224/FP16/frozen-model.xml"

else:
    print("Specify the target device to infer on; CPU, GPU, MYRIAD is acceptable.")
    sys.exit(0)
```

**Comment by PINTO0309** [comment]
For Windows. Please show below.
https://github.com/PINTO0309/OpenVINO-DeeplabV3/issues/1

**Comment by Ealuthwala** [comment]
I am getting the exact same error, I tried removing the  `if platform.processor() == "x86_64":` to make it use the extension, but still no use, 
![image](https://user-images.githubusercontent.com/30061526/71444205-7c053280-274a-11ea-8284-ae281ac3cf77.png) now I am getting this error, anyway, I don't think I was supposed to do that. so how can I fix this?

I am using windows 10 with the openvino 2019.1.133.
tried using the tflite one too. that just produce random dots

**Comment by Ealuthwala** [comment]
and the platform.processor() is 'Intel64 Family 6 Model 60 Stepping 3, GenuineIntel'
