### ISSUE TITLE
TFlite Models won't produce any pose, only random points everywhere

### ISSUE THREAD

**Issue by JimWest** [PINTO0309/MobileNetV2-PoseEstimation#3]
The Openvino scripts and models are working pretty good, but the tflite ones (normal tflite and edge tpu) are only producing random points as poses everyhere in the picture, no matter if there are people visible, or not.

I'll attach a Screenshot to show the problem:

![tflite_problem](https://user-images.githubusercontent.com/1804137/67385376-51a0c880-f593-11e9-81f2-57c79ade3a8a.PNG)

**Comment by Ealuthwala** [comment]
did you figure it out?

**Comment by PINTO0309** [comment]
Bug fixed.
Weight Quantization, Integer Quantization, Float16 Quantization. 256x256.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/07_mobilenetv2-poseestimation/dm100_224**
