### ISSUE TITLE
OpenVINO 2022.1 not supported

### ISSUE THREAD

**Issue by cansik** [PINTO0309/MobileNetV2-PoseEstimation#7]
OpenVINO 2022.1 seems not to be supported. Would it be possible to re-convert the files with the newest version?

```
RuntimeError: The support of IR v5 has been removed from the product. Please, convert the original model using the Model Optimizer which comes with this version of the OpenVINO to generate supported IR version.
```

I tried to convert the model with the 2022.1 open model optimizer, but it seems that it does not work. I used the frozen model form the checkpoint path and after conversion the bin file is only 2.2MB (v1.4). And the results are completely wrong, it seems there are weights missing.

Could you give me a hint how to convert it for more recent OpenVINO versions?

**Comment by PINTO0309** [comment]
I think you should first read the official OpenVINO tutorial.

https://github.com/PINTO0309/PINTO_model_zoo/tree/main/007_mobilenetv2-poseestimation
```bash
docker run -it --rm \
-v `pwd`:/home/user/workdir \
ghcr.io/pinto0309/openvino2tensorflow:latest

pb_to_saved_model \
--pb_file_path frozen-model.pb \
--inputs image:0 \
--outputs Openpose/concat_stage7:0

mo \
--framework tf \
--saved_model_dir saved_model_from_pb \
--output_dir openvino/FP32 \
--data_type FP32 \
--model_name mobilenetv2_pose
```
